version: "3.8"

services:
  linkage-widget:
    build:
      context: ../
      dockerfile: docker/image/Dockerfile
    command: npm run start
    container_name: linkage-widget
    env_file:
      - ../.env
    environment:
      - MODELICAPATH=/app/dependencies/ModelicaStandardLibrary:/app/dependencies/modelica-buildings
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ../:/app
