version: "3.8"

services:
  linkage-widget:
    build:
      context: ../
      dockerfile: docker/image/Dockerfile
    command: npm run start
    container_name: linkage-widget
    environment:
      - MODELICAPATH=/app/dependencies/ModelicaStandardLibrary:/app/dependencies/modelica-buildings
    ports:
      - 3000:3000
    volumes:
      - ../:/app
